services:
  # Auth microservice
  auth-service:
    image: nestjs-recipe
    command: ['bun', '--bun', 'start:auth:prod']
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    networks:
      - nestjs-recipe-network
    restart: unless-stopped

  # Recipe microservice
  recipe-service:
    image: nestjs-recipe
    command: ['bun', '--bun', 'start:recipe:prod']
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    networks:
      - nestjs-recipe-network
    restart: unless-stopped

  # Users microservice
  users-service:
    image: nestjs-recipe
    command: ['bun', '--bun', 'start:users:prod']
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    networks:
      - nestjs-recipe-network
    restart: unless-stopped

  # API Gateway
  api-gateway:
    image: nestjs-recipe
    command: ['bun', '--bun', 'start:gateway:prod']
    environment:
      - NODE_ENV=production
      - AUTH_SERVICE_HOST=auth-service
      - RECIPE_SERVICE_HOST=recipe-service
      - USERS_SERVICE_HOST=users-service
    env_file:
      - .env
    ports:
      - '3000:3000'
    networks:
      - nestjs-recipe-network
    depends_on:
      - auth-service
      - recipe-service
      - users-service
    restart: unless-stopped

networks:
  nestjs-recipe-network:
    driver: bridge
